name: sync-erlang-versions
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'
permissions:
  contents: read
jobs:
  sync-versions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - shell: pwsh
        run: ${{ github.workspace }}\sync-versions.ps1 -ApiKey ${{ secrets.CHOCOLATEY_API_KEY }}
